---

- name: Install restic
  include_tasks: 'install_{{ restic_install_method }}.yml'

- name: Ensure restic directories exist
  file:
    state: 'directory'
    path:  '{{ item }}'
    mode: '0755'
    owner: 'root'
    group: 'root'
  with_items:
    - '/var/lib/restic'
    - '/var/log/restic'

- name: Configure restic jobs
  include_tasks: 'configure.yml'
  with_items: '{{ restic_repos | default([]) }}'
