---

- name: Ensure restic directories exist
  file:
    state: 'directory'
    path: '{{ item }}'
    mode: '0755'
    owner: 'root'
    group: 'root'
  with_items:
    - '/var/log/restic'
    - '{{ restic_download_path }}/bin'

- name: Install restic
  include_tasks: 'install.yml'

- name: Configure restic jobs
  include_tasks: 'configure.yml'
  with_items: '{{ restic_repos | default([]) }}'
