---

- name: Install restic
  include_tasks: 'install_{{ restic_install_method }}.yml'

- name: Ensure restic directories exist
  file:
    state: 'directory'
    path:  '{{ item }}'
    mode: '0755'
    owner: 'root'
    group: 'root'
  with_items:
    - '/var/lib/restic'
    - '/var/log/restic'

- name: Deploy password file
  copy:
    content: '{{ vault_repo_password }}'
    dest: '/var/lib/restic/repopw'
    mode: '0600'
    owner: 'root'
    group: 'root'
  no_log: true
  ignore_errors: true

- name: Deploy cron script
  template:
    src: 'restic.cron.j2'
    dest: '/etc/cron.d/restic'
    mode: '0644'
